### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [usehero/hero-messenger-gtm-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation link [https://github.com/usehero/hero-messenger-gtm-template](https://github.com/usehero/hero-messenger-gtm-template) provided in the manifest redirects user to the Github page. It does not provide any information regarding the template. 

![Screenshot 2020-07-21 at 12 24 54 PM](https://user-images.githubusercontent.com/53495700/88097564-31fff600-cb4d-11ea-9fce-378a1757d44a.png)

**Comment by hero-oss-dev** [comment]
Hi @praveena-pappu. Thanks for your feedback! I have updated the project README.md file to include instructions on how to add, configure and save the tag.
